// Handles actually running your application
// Generated by Spring Initializr
// No need to mess with anything in here
package org.wecancodeit.studentroster;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class StudentRosterApplication {

	public static void main(String[] args) {
		SpringApplication.run(StudentRosterApplication.class, args);
	}
}
